name: stanford
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy=1.22.3
  - matplotlib=3.5
  - scipy=1.9.1 # 1.7.3
  - pip=22.1.2
  - pandas=1.4.3
  - pip:
    - tqdm==4.64.0
    - vtk==9.1.0
    - argparse==1.4.0
    - ray==2.0.0
    - torch==1.12.1
    - pytorch-lightning==1.7.3