name: stenosis-tool
channels:
  - defaults
dependencies:
  - pip=22.1.2
  - python=3.9.13
  - setuptools=63.4.1
  - pip:
    - tqdm==4.64.0
    - vtk==9.1.0
    - argparse==1.4.0
    - numpy==1.22.3
    - matplotlib==3.5
    - pandas==1.4.3
    - torch==1.12.1
    - pytorch-lightning==1.7.3
    - scipy==1.9.1
    - ipykernel==6.15.2
    - ipython==8.5.0
    - ipywidgets==8.0.2